In [1]:
# upload_pp.py
import psycopg2

In [7]:
import pandas as pd

results = pd.read_csv('pp-complete.csv')
print(results)

          {F887F88E-7D15-4415-804E-52EAC2F10958}   70000  1995-07-07 00:00  \
0         {40FD4DF2-5362-407C-92BC-566E2CCE89E9}   44500  1995-02-03 00:00
1         {7A99F89E-7D81-4E45-ABD5-566E49A045EA}   56500  1995-01-13 00:00
2         {28225260-E61C-4E57-8B56-566E5285B1C1}   58000  1995-07-28 00:00
3         {444D34D7-9BA6-43A7-B695-4F48980E0176}   51000  1995-06-28 00:00
4         {AE76CAF1-F8CC-43F9-8F63-4F48A2857D41}   17000  1995-03-10 00:00
...                                          ...     ...               ...
28497121  {01EB45EF-E9C5-40F3-E063-4704A8C05FDE}  275000  2023-06-16 00:00
28497122  {01EB45EF-E9C6-40F3-E063-4704A8C05FDE}  320000  2023-06-05 00:00
28497123  {01EB45EF-E9C7-40F3-E063-4704A8C05FDE}   83000  2023-02-03 00:00
28497124  {01EB45EF-E9C8-40F3-E063-4704A8C05FDE}  190000  2023-06-30 00:00
28497125  {01EB45EF-E9C9-40F3-E063-4704A8C05FDE}  682500  2023-06-23 00:00

          MK15 9HP  D  N  F   31 Unnamed: 8        ALDRICH DRIVE  \
0          SR6 0AQ  T  N  F   50        NaN          HOWICK PARK
1          CO6 1SQ  T  N  F   19        NaN     BRICK KILN CLOSE
2          B90 4TG  T  N  F   37        NaN     RAINSBROOK DRIVE
3          DY5 1SA  S  N  F   59        NaN           MERRY HILL
4          S65 1QJ  T  N  L   22        NaN        DENMAN STREET
...            ... .. .. ..  ...        ...                  ...
28497121  LE18 4YF  S  N  F   69        NaN  GLOUCESTER CRESCENT
28497122  LE65 2NU  D  N  F  138        NaN             WOODSIDE
28497123  LE10 2SE  F  N  L   20        NaN          TILTON ROAD
28497124  LE12 9HT  T  N  F   16        NaN           KINGS ROAD
28497125  LE16 7SE  D  N  F    4        NaN         FERNIE CHASE

                  WILLEN      MILTON KEYNES            MILTON KEYNES.1  \
0             SUNDERLAND         SUNDERLAND                 SUNDERLAND
1             COGGESHALL         COLCHESTER                  BRAINTREE
2                SHIRLEY           SOLIHULL                   SOLIHULL
3          BRIERLEY HILL      BRIERLEY HILL                     DUDLEY
4              ROTHERHAM          ROTHERHAM                  ROTHERHAM
...                  ...                ...                        ...
28497121             NaN            WIGSTON          OADBY AND WIGSTON
28497122             NaN  ASHBY-DE-LA-ZOUCH  NORTH WEST LEICESTERSHIRE
28497123         BURBAGE           HINCKLEY      HINCKLEY AND BOSWORTH
28497124        SHEPSHED       LOUGHBOROUGH                  CHARNWOOD
28497125  THORPE LANGTON  MARKET HARBOROUGH                 HARBOROUGH

          MILTON KEYNES.2  A A.1
0           TYNE AND WEAR  A   A
1                   ESSEX  A   A
2           WEST MIDLANDS  A   A
3           WEST MIDLANDS  A   A
4         SOUTH YORKSHIRE  A   A
...                   ... ..  ..
28497121   LEICESTERSHIRE  A   A
28497122   LEICESTERSHIRE  A   A
28497123   LEICESTERSHIRE  A   A
28497124   LEICESTERSHIRE  A   A
28497125   LEICESTERSHIRE  A   A

[28497126 rows x 16 columns]

In [9]:
from collections import namedtuple
import sys
import csv

# upload the lines set nstart and nend as follows:
nstart = 1
nend   = 28497126

conn = psycopg2.connect(database='house_prices', user='postgres', password='Kirt')
cursor = conn.cursor()

Field = namedtuple('Field', 'name index type max_length')

def parse_date(s):
    return s[:10]

def strip_nonascii(s):
    return ''.join([c if ord(c) < 128 else ' ' for c in s])

price = Field('price', 1, str, None)
date_of_transfer = Field('date_of_transfer', 2, parse_date, None)
postcode = Field('postcode', 3, str, 8)
paon = Field('paon', 7, str, 100)
saon = Field('saon', 8, strip_nonascii, 100)
street = Field('street', 9, str, 200)
locality = Field('locality', 10, str, 200)
town_city = Field('town_city', 11, str, 100)
district = Field('district', 12, str, 100)
county = Field('county', 12, str, 60)

output_fields = [price, date_of_transfer, postcode, paon, saon, street, locality, town_city, district, county]
field_names = [field.name for field in output_fields]
cs_field_names = ', '.join(field_names)

pp_name = 'pp-complete.csv'

with open(pp_name, encoding='cp1252') as pp_file:
    pp_reader = csv.reader(pp_file)

    for row in pp_reader:
        if pp_reader.line_num < nstart:
            continue
        if pp_reader.line_num > nend:
            break

        data = []
        for field in output_fields:
            s = row[field.index]
            field_value = field.type(s)
            data.append(field_value)

        query = 'INSERT INTO pp ({0:s}) VALUES ({1:s});'.format(cs_field_names, ','.join(['%s']*10))
        cursor.execute(query, data)

        if not pp_reader.line_num % 100000:
            print(pp_reader.line_num)
conn.commit()

100000
200000
300000
400000
500000
600000
700000
800000
900000
1000000
1100000
1200000
1300000
1400000
1500000
1600000
1700000
1800000
1900000
2000000
2100000
2200000
2300000
2400000
2500000
2600000
2700000
2800000
2900000
3000000
3100000
3200000
3300000
3400000
3500000
3600000
3700000
3800000
3900000
4000000
4100000
4200000
4300000
4400000
4500000
4600000
4700000
4800000
4900000
5000000
5100000
5200000
5300000
5400000
5500000
5600000
5700000
5800000
5900000
6000000
6100000
6200000
6300000
6400000
6500000
6600000
6700000
6800000
6900000
7000000
7100000
7200000
7300000
7400000
7500000
7600000
7700000
7800000
7900000
8000000
8100000
8200000
8300000
8400000
8500000
8600000
8700000
8800000
8900000
9000000
9100000
9200000
9300000
9400000
9500000
9600000
9700000
9800000
9900000
10000000
10100000
10200000
10300000
10400000
10500000
10600000
10700000
10800000
10900000
11000000
11100000
11200000
11300000
11400000
11500000
11600000
11700000
11800000
11900000
12000000
12100000
12200000
12300000
12400000
12500000
12600000
12700000
12800000
12900000
13000000
13100000
13200000
13300000
13400000
13500000
13600000
13700000
13800000
13900000
14000000
14100000
14200000
14300000
14400000
14500000
14600000
14700000
14800000
14900000
15000000
15100000
15200000
15300000
15400000
15500000
15600000
15700000
15800000
15900000
16000000
16100000
16200000
16300000
16400000
16500000
16600000
16700000
16800000
16900000
17000000
17100000
17200000
17300000
17400000
17500000
17600000
17700000
17800000
17900000
18000000
18100000
18200000
18300000
18400000
18500000
18600000
18700000
18800000
18900000
19000000
19100000
19200000
19300000
19400000
19500000
19600000
19700000
19800000
19900000
20000000
20100000
20200000
20300000
20400000
20500000
20600000
20700000
20800000
20900000
21000000
21100000
21200000
21300000
21400000
21500000
21600000
21700000
21800000
21900000
22000000
22100000
22200000
22300000
22400000
22500000
22600000
22700000
22800000
22900000
23000000
23100000
23200000
23300000
23400000
23500000
23600000
23700000
23800000
23900000
24000000
24100000
24200000
24300000
24400000
24500000
24600000
24700000
24800000
24900000
25000000
25100000
25200000
25300000
25400000
25500000
25600000
25700000
25800000
25900000
26000000
26100000
26200000
26300000
26400000
26500000
26600000
26700000
26800000
26900000
27000000
27100000
27200000
27300000
27400000
27500000
27600000
27700000
27800000
27900000
28000000
28100000
28200000
28300000
28400000